In [6]:
import pandas as pd
import numpy as np

df=pd.read_csv("/content/parkinsons data.csv")
df.head()

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [10]:
df.info()
df.shape
df.tail()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [11]:
df.describe()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,154.228641,197.104918,116.324631,0.006220,0.000044,0.003306,0.003446,0.009920,0.029709,0.282251,...,0.046993,0.024847,21.885974,0.753846,0.498536,0.718099,-5.684397,0.226510,2.381826,0.206552
std,41.390065,91.491548,43.521413,0.004848,0.000035,0.002968,0.002759,0.008903,0.018857,0.194877,...,0.030459,0.040418,4.425764,0.431878,0.103942,0.055336,1.090208,0.083406,0.382799,0.090119
min,88.333000,102.145000,65.476000,0.001680,0.000007,0.000680,0.000920,0.002040,0.009540,0.085000,...,0.013640,0.000650,8.441000,0.000000,0.256570,0.574282,-7.964984,0.006274,1.423287,0.044539
25%,117.572000,134.862500,84.291000,0.003460,0.000020,0.001660,0.001860,0.004985,0.016505,0.148500,...,0.024735,0.005925,19.198000,1.000000,0.421306,0.674758,-6.450096,0.174351,2.099125,0.137451
50%,148.790000,175.829000,104.315000,0.004940,0.000030,0.002500,0.002690,0.007490,0.022970,0.221000,...,0.038360,0.011660,22.085000,1.000000,0.495954,0.722254,-5.720868,0.218885,2.361532,0.194052
75%,182.769000,224.205500,140.018500,0.007365,0.000060,0.003835,0.003955,0.011505,0.037885,0.350000,...,0.060795,0.025640,25.075500,1.000000,0.587562,0.761881,-5.046192,0.279234,2.636456,0.252980
max,260.105000,592.030000,239.170000,0.033160,0.000260,0.021440,0.019580,0.064330,0.119080,1.302000,...,0.169420,0.314820,33.047000,1.000000,0.685151,0.825288,-2.434031,0.450493,3.671155,0.527367

In [12]:
df['status'].value_counts()

status
1    147
0     48
Name: count, dtype: int64

In [13]:
X=df.drop(columns=['name','status'],axis=1)
Y=df['status']

In [14]:
X.head()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,...,0.02971,0.06545,0.02211,21.033,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,...,0.04368,0.09403,0.01929,19.085,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,...,0.03590,0.08270,0.01309,20.651,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,...,0.03772,0.08771,0.01353,20.644,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,...,0.04465,0.10470,0.01767,19.649,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [15]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: status, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2, random_state=2)

In [19]:
X_train

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
123,182.018,197.173,79.187,0.00842,0.00005,0.00506,0.00449,0.01517,0.02503,0.231,...,0.01931,0.04115,0.01813,18.784,0.589956,0.732903,-5.445140,0.142466,2.174306,0.215558
160,114.238,124.393,77.022,0.00581,0.00005,0.00299,0.00316,0.00896,0.04009,0.406,...,0.04114,0.04736,0.02073,20.437,0.653139,0.694571,-5.185987,0.259229,2.151121,0.244948
94,157.821,172.975,68.401,0.00358,0.00002,0.00196,0.00196,0.00587,0.03716,0.307,...,0.02764,0.06185,0.00850,22.219,0.502380,0.712170,-6.251425,0.188056,2.143851,0.160812
57,117.274,129.916,110.402,0.00752,0.00006,0.00299,0.00469,0.00898,0.02293,0.221,...,0.01948,0.03568,0.00681,22.817,0.530529,0.817756,-4.608260,0.290024,2.021591,0.314464
41,184.055,196.537,166.977,0.00258,0.00001,0.00134,0.00147,0.00403,0.01463,0.132,...,0.01234,0.02226,0.00257,26.453,0.306443,0.759203,-7.044105,0.063412,2.361532,0.115730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,241.404,248.834,232.483,0.00281,0.00001,0.00157,0.00173,0.00470,0.01760,0.154,...,0.01251,0.03017,0.00675,23.145,0.457702,0.634267,-6.793547,0.158266,2.256699,0.117399
22,167.930,193.221,79.068,0.00442,0.00003,0.00220,0.00247,0.00661,0.04351,0.377,...,0.04246,0.06685,0.01280,22.468,0.619060,0.679834,-4.330956,0.262384,2.916777,0.285695
72,120.080,139.710,111.208,0.00405,0.00003,0.00180,0.00220,0.00540,0.01706,0.152,...,0.01345,0.02921,0.00442,25.742,0.495954,0.762959,-5.791820,0.329066,2.205024,0.188180
15,142.167,217.455,83.159,0.00369,0.00003,0.00157,0.00203,0.00471,0.01503,0.126,...,0.01359,0.02316,0.00839,25.175,0.565924,0.658245,-5.340115,0.210185,2.205546,0.234589
168,197.569,217.627,90.794,0.00803,0.00004,0.00490,0.00448,0.01470,0.02177,0.189,...,0.01439,0.03836,0.01337,19.269,0.372222,0.725216,-5.736781,0.164529,2.882450,0.202879

In [20]:
Y_train

123    1
160    1
94     1
57     1
41     1
      ..
43     0
22     1
72     1
15     1
168    0
Name: status, Length: 156, dtype: int64

In [23]:
#df standardization
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit_transform(X_train)
scaler.fit_transform(X_test)

array([[-1.27434768e+00, -7.92100902e-01, -6.42064804e-01,
        -3.70550081e-02,  7.65593976e-01, -5.36663194e-02,
         2.70521702e-01, -5.17113412e-02, -1.73362776e-01,
        -1.84537779e-01, -2.46162360e-01, -9.53432617e-02,
         3.51764171e-02, -2.46253875e-01, -2.42578071e-01,
        -5.71526263e-01,  1.17904437e+00,  1.05108661e+00,
         5.45105104e-01,  2.12053870e+00,  2.20220746e-01,
         6.73407367e-01],
       [-9.93036290e-01, -7.55457877e-01, -6.02839911e-01,
         2.21517439e+00,  2.37519856e+00,  2.52231701e+00,
         1.86180632e+00,  2.52056878e+00,  6.63120841e-01,
         1.31330947e+00,  8.25344625e-01,  4.41243374e-01,
         3.16150237e-01,  8.25821477e-01,  7.63822230e-01,
        -1.17294582e+00,  9.93607948e-01,  1.27956439e+00,
         9.15137942e-01,  4.60066283e-01,  1.91967718e-01,
         1.05151668e+00],
       [-9.59040068e-01, -4.67857304e-01, -5.93333267e-01,
         1.66162458e+00,  1.97279742e+00,  1.61932286e+00,
         1.11791311e+00,  1.62190467e+00,  4.00543673e-01,
         5.00453343e-01,  5.25816736e-01,  1.61390934e-01,
         2.41072212e-01,  5.25249223e-01,  2.35076464e+00,
        -1.40906100e+00,  1.84596231e+00, -6.11543016e-01,
         3.10139928e+00,  2.19665622e+00,  7.06756892e-01,
         2.24832219e+00],
       [ 1.21655984e+00,  3.42592697e-01,  1.07869105e+00,
        -5.82153680e-01, -8.44010610e-01, -5.57663059e-01,
        -4.73371514e-01, -5.58231110e-01,  1.01037273e+00,
         7.28783717e-01,  1.26074083e+00,  7.97751048e-01,
         7.60930655e-01,  1.26072482e+00,  2.94041445e-01,
        -1.32910167e+00,  1.12519585e+00, -8.21462403e-01,
         1.75508525e-01,  1.05701369e+00,  4.05211189e-01,
         1.38882940e-01],
       [-6.35974168e-01,  4.29350995e+00, -5.84652129e-01,
        -7.50851481e-02, -3.92083168e-02, -5.36663194e-02,
        -1.62876954e-01, -5.40455337e-02, -5.86472783e-01,
        -5.77266023e-01, -6.46047531e-01, -5.45540666e-01,
        -4.20979460e-01, -6.46159084e-01, -2.20102630e-02,
         3.19001125e-01,  6.84034296e-01, -7.24595416e-01,
        -7.56346058e-01, -1.02927424e+00, -5.59516433e-01,
        -1.05756066e+00],
       [-5.86416135e-01, -6.70385007e-01,  4.40113311e-02,
        -7.72304380e-01, -4.41609463e-01, -6.55662424e-01,
        -7.57991527e-01, -6.56267195e-01, -1.11419302e+00,
        -1.07959285e+00, -1.15555373e+00, -9.72619824e-01,
        -1.08985641e+00, -1.15517614e+00, -8.74681486e-01,
         8.39834221e-01, -2.47332587e-01,  1.82736825e-01,
        -7.75090892e-01, -6.92642384e-01, -9.63432093e-01,
        -7.78522740e-01],
       [ 1.28455229e+00,  2.50110664e-01,  2.33071875e+00,
        -1.33430534e+00, -1.24641176e+00, -1.09665957e+00,
        -1.12023518e+00, -1.09976377e+00, -9.85042686e-01,
        -1.00652713e+00, -1.00733375e+00, -8.03491611e-01,
        -1.02842893e+00, -1.00746340e+00, -1.22701708e+00,
         2.75666307e+00, -1.77559440e+00,  5.04170261e-01,
        -2.23981105e+00, -8.05679021e-01,  3.46537934e-01,
        -1.90196636e+00],
       [-7.12652275e-01, -6.00989033e-01, -1.99992536e-01,
        -4.97317214e-02, -3.92083168e-02, -3.26664553e-02,
         1.54086243e-01, -3.07036088e-02,  2.50885872e+00,
         2.36362920e+00,  2.55920967e+00,  2.34423997e+00,
         2.58555416e+00,  2.55977340e+00,  2.16743555e+00,
        -1.94212317e+00,  1.33652694e+00, -5.42182542e-02,
         1.20045933e+00,  9.69035939e-01,  1.06246985e+00,
         1.00378386e+00],
       [-9.10929645e-01,  2.01744415e-01, -8.04609779e-01,
         5.03818093e-01,  7.65593976e-01,  3.80330873e-01,
         5.61610352e-01,  3.80114269e-01,  1.21564478e+00,
         1.49597377e+00,  7.62042339e-01,  1.00338175e+00,
         2.18286294e+00,  7.62516020e-01,  1.40069984e+00,
        -2.74265712e-01,  2.00482533e-01,  4.25796211e-01,
         1.90288467e-01,  7.78089750e-02,  1.61541380e+00,
         2.68248119e-01],
       [-6.33124185e-01, -5.92074719e-01,  8.97870211e-02,
         2.26588124e+00,  1.97279742e+00,  1.97632055e+00,
         3.18787684e+00,  1.97903612e+00,  2.46951491e+00,
         2.41842848e+00,  2.34459949e+00,  2.96599908e+00,
         1.96672923e+00,  2.34412311e+00, -1.06036095e-01,
        -7.17961576e-01, -8.27455211e-01,  1.85515298e+00,
         1.43369839e+00,  1.06267215e+00,  1.34979383e-02,
         1.78454581e+00],
       [-1.75226960e-01, -2.87281497e-01,  6.14942566e-01,
        -9.32876082e-01, -8.44010610e-01, -1.00566016e+00,
        -8.74426987e-01, -1.00406188e+00, -9.29448171e-01,
        -9.60861051e-01, -8.99256675e-01, -8.55811849e-01,
        -8.20258045e-01, -8.99380915e-01, -8.01158884e-01,
         8.66173763e-01, -4.87525340e-01, -1.06512731e+00,
        -8.84171177e-01, -1.03586031e+00, -9.42935858e-01,
        -8.17529337e-01],
       [-5.79992365e-01, -6.30000302e-01,  2.75011928e-02,
        -3.11717130e-01, -3.92083168e-02, -3.33664508e-01,
        -6.22150157e-01, -3.36482824e-01, -1.12274602e+00,
        -1.08872606e+00, -1.08144374e+00, -1.03467406e+00,
        -1.19451062e+00, -1.08157711e+00,  2.90222089e-01,
         1.22332542e+00, -5.21391012e-01, -1.98725012e-01,
        -1.26190245e+00, -1.03416410e+00, -3.01828763e-02,
        -1.16143080e+00],
       [ 1.30898071e+00,  5.76421195e-01,  1.49083203e+00,
        -1.09767335e+00, -1.24641176e+00, -1.13165934e+00,
        -1.00379972e+00, -1.13010827e+00,  2.70538039e-01,
         9.85918846e-02,  3.65245084e-01,  1.67474682e-01,
         1.64856641e-01,  3.65698882e-01, -3.54294234e-01,
        -7.08868163e-01, -7.92330870e-02, -1.33412590e+00,
        -4.27547449e-01, -1.37344934e-01,  7.58048324e-01,
        -5.32486281e-01],
       [-6.33259899e-01, -5.20421017e-01,  8.47540918e-02,
         2.04192597e+00,  1.97279742e+00,  1.68232245e+00,
         2.65097999e+00,  1.68025948e+00,  2.69103767e+00,
         2.73809101e+00,  2.60244050e+00,  3.14486130e+00,
         2.17376257e+00,  2.60197704e+00, -6.40231788e-02,
        -7.20156538e-01, -7.71281813e-01,  1.75609302e+00,
         1.79248653e+00,  1.36711573e+00,  2.14631153e-01,
         2.27167253e+00],
       [-5.08584464e-01, -6.18573869e-01,  2.01896186e-01,
         4.32308428e-02, -3.92083168e-02, -6.48662470e-01,
        -5.50995154e-01, -6.49264617e-01, -6.26671893e-01,
        -6.77731387e-01, -5.92008995e-01, -7.84023615e-01,
        -4.86957118e-01, -5.91603161e-01, -5.54810423e-01,
         6.94026040e-02,  8.29870355e-01,  3.55604876e-01,
        -7.65466744e-01,  4.69249682e-01, -8.20133218e-01,
        -8.79792445e-01],
       [ 4.04767144e-01,  1.20593418e-01, -8.13610467e-01,
        -4.97317214e-02, -4.41609463e-01,  1.28332503e-01,
        -2.27563321e-01,  1.30355673e-01, -4.74428454e-01,
        -4.49401013e-01, -6.87734403e-01, -4.42116938e-01,
        -7.06153448e-02, -6.87333365e-01, -2.38758715e-01,
         8.58334614e-01, -8.50814664e-01,  1.94208993e-01,
        -9.81757788e-01, -2.79813502e-01, -1.20769002e+00,
        -8.61361493e-01],
       [ 1.84843477e-01, -2.50829266e-01, -8.61383351e-01,
        -9.28650511e-01, -8.44010610e-01, -9.84660296e-01,
        -9.00301533e-01, -9.83054143e-01, -4.42782345e-01,
        -5.40733163e-01, -2.69321733e-01, -5.45540666e-01,
        -6.99678187e-01, -2.69929087e-01, -7.74423392e-01,
         6.21278732e-01, -3.30419175e-01, -9.47607148e-01,
        -3.97180046e-01, -3.62146049e-01, -6.74924539e-01,
        -3.94113393e-01],
       [ 1.63858348e+00,  4.93012471e-01, -3.78275400e-01,
        -4.63837689e-01, -8.44010610e-01, -9.42660568e-01,
        -1.03614290e+00, -9.43372870e-01, -8.95236163e-01,
        -8.51262471e-01, -8.63745636e-01, -9.60452327e-01,
        -8.94198524e-01, -8.63353418e-01, -7.05674984e-01,
         5.14352732e-01, -4.66313627e-01, -2.11474061e+00,
         2.50516507e-01,  2.09791813e+00,  1.86801958e+00,
         2.83569267e-01],
       [-5.52035391e-01, -5.27067004e-01,  1.76731540e-01,
        -7.63853238e-01, -4.41609463e-01, -7.46661836e-01,
        -5.57463790e-01, -7.44966509e-01, -6.30948394e-01,
        -7.05131032e-01, -7.09349817e-01, -5.88126907e-01,
        -5.80235876e-01, -7.09464542e-01, -7.76333070e-01,
         6.09990356e-01,  1.01190803e+00,  8.53981354e-01,
         1.21457522e-01,  3.53827746e-01, -1.53555353e+00,
         1.64257335e-01],
       [ 6.61469160e-01,  6.11187265e-02, -5.85930334e-01,
        -1.59596570e-01, -4.41609463e-01, -2.84664825e-01,
        -1.95220137e-01, -2.85130590e-01,  1.57914738e+00,
         1.34070912e+00,  1.46454332e+00,  1.27715045e+00,
         2.17376257e+00,  1.46505220e+00,  4.00983412e-01,
        -7.89768186e-01,  3.61208860e-01, -4.09724518e-01,
         5.46200159e-01, -2.74340568e-01,  6.65719932e-01,
         7.24558286e-01],
       [ 1.65481690e-01, -3.14066837e-01,  6.57043419e-01,
        -1.43571904e+00, -1.24641176e+00, -1.30665821e+00,
        -1.24313928e+00, -1.30750690e+00, -1.13044372e+00,
        -1.13439214e+00, -1.20959227e+00, -1.02737356e+00,
        -9.87477282e-01, -1.21024674e+00, -1.12866866e+00,
         2.19099004e+00, -2.13963654e+00, -5.86929408e-01,
        -1.09569421e+00, -9.31530011e-01, -1.30725651e-01,
        -1.13094936e+00],
       [ 1.31488425e+00,  4.72099342e-01, -5.84545612e-01,
        -6.07507107e-01, -8.44010610e-01, -5.08663376e-01,
        -4.99246060e-01, -5.06878876e-01, -2.98236608e-01,
        -3.39802434e-01, -1.87491949e-01, -2.96106969e-01,
        -4.03916272e-01, -1.88095203e-01,  5.63306041e-01,
        -1.33380516e+00,  3.48344554e-01, -1.29776192e+00,
        -1.69768793e-01, -2.33604973e-01,  4.21792485e-01,
        -1.40342637e-01],
       [-5.56310365e-01, -6.39550596e-01, -6.70060345e-02,
        -1.03006422e+00, -8.44010610e-01, -1.01966007e+00,
        -9.90862447e-01, -1.01806703e+00, -1.13215432e+00,
        -1.16179178e+00, -1.17716915e+00, -1.01277257e+00,
        -1.08985641e+00, -1.17730731e+00, -8.90913749e-01,
         1.07500871e+00, -1.47152636e-01,  1.13069184e-01,
        -1.62484582e-01, -4.63879023e-01, -7.28135309e-01,
        -2.13530273e-01],
       [-6.25840896e-01, -4.50516260e-01, -2.19964477e-01,
        -6.79341816e-01, -4.41609463e-01, -5.99662787e-01,
        -4.53965604e-01, -6.00246575e-01, -5.89038683e-01,
        -6.59464957e-01, -5.51866082e-01, -4.36033189e-01,
        -6.17774888e-01, -5.51972915e-01, -7.92565333e-01,
         7.85273740e-01, -1.29700237e+00,  7.29113114e-01,
        -2.95233043e-01, -2.23072963e-02, -1.47784312e+00,
        -4.87702418e-01],
       [ 2.22070376e+00,  7.21466942e-01,  3.18826066e+00,
        -1.22021492e+00, -1.28665187e+00, -1.01266011e+00,
        -9.64987900e-01, -1.01573284e+00, -7.28452619e-01,
        -7.59930322e-01, -6.04360660e-01, -6.58698391e-01,
        -9.63588819e-01, -6.03955445e-01, -9.01416978e-01,
         6.55770990e-01, -8.12066755e-01, -1.19470879e+00,
        -1.37845754e+00, -1.70811689e+00,  8.83044317e-02,
        -1.29748474e+00],
       [-3.55861580e-01,  3.10281835e+00, -5.30781146e-01,
         2.84088396e-01,  3.63192830e-01, -1.44665731e-01,
         1.67023516e-01, -1.45079041e-01, -2.88828306e-01,
         3.46593799e-02, -6.01272744e-01, -3.69111953e-01,
        -1.44555824e-01, -6.00867374e-01,  8.87951300e-01,
         5.65150421e-01, -1.86885849e-01, -4.54958570e-01,
        -4.86447982e-01,  6.48690374e-01,  1.10657013e+00,
        -6.30994695e-01],
       [-7.00234493e-01, -7.47550531e-01, -3.00118536e-01,
        -6.96244100e-01, -4.41609463e-01, -6.34662560e-01,
        -5.50995154e-01, -6.32925270e-01, -7.47269224e-01,
        -7.69063537e-01, -7.57212521e-01, -6.27062898e-01,
        -8.11157679e-01, -7.56814965e-01, -8.99507300e-01,
         1.13082345e+00, -1.37703341e+00,  8.96335091e-01,
        -2.19154243e-01, -5.14579864e-01, -1.54268113e+00,
        -2.65740135e-01],
       [ 1.13338141e-02,  1.18081299e-01, -7.33536296e-01,
         9.26375203e-01,  3.63192830e-01,  1.06632643e+00,
         8.65636275e-01,  1.06636686e+00,  1.39479728e-02,
         1.44257959e-01, -5.30488199e-03,  9.08194486e-02,
         9.43288002e-02, -4.86965059e-03,  4.33447938e-01,
        -1.28049895e+00,  1.47110397e+00,  3.86486445e-01,
         1.65575911e-01, -1.36533627e+00, -1.81782324e+00,
         3.11168780e-01],
       [-1.12228075e+00, -7.08755776e-01, -4.51559111e-01,
         7.70354116e-02,  7.65593976e-01,  4.43330465e-02,
         2.83458976e-01,  4.16563582e-02,  4.21070878e-01,
         3.45188689e-01,  3.12750505e-01,  3.70671889e-01,
         6.63101714e-01,  3.13201673e-01, -3.80074886e-01,
        -3.38233172e-01,  4.69404093e-01,  1.41615028e+00,
         8.07181356e-01,  1.25910147e+00,  3.01185643e-01,
         9.63235768e-01],
       [-7.35633088e-01, -5.86160109e-01, -2.83768173e-01,
         2.21029873e-02,  3.63192830e-01,  2.05332005e-01,
        -2.70355840e-02,  2.05049832e-01, -5.04363961e-01,
        -5.68132808e-01, -4.19085677e-01, -4.71318931e-01,
        -5.66585326e-01, -4.18671179e-01,  1.42736188e-02,
        -5.39856099e-01,  5.80200971e-01, -6.35698393e-01,
         1.40403962e-01, -6.10707386e-01, -1.48125916e+00,
         1.72702062e-01],
       [-8.11248106e-01, -5.54498924e-01, -1.41381545e-01,
         1.04469119e+00,  1.16799512e+00,  6.11329378e-01,
         1.27962902e+00,  6.08865132e-01,  3.19290152e-01,
         3.45188689e-01,  3.77596749e-01,  2.29528919e-01,
         2.34246937e-01,  3.78051167e-01, -3.66707140e-01,
        -5.99747201e-01,  3.47314967e-01,  1.75277084e+00,
         1.20632129e+00, -3.36901642e-01, -1.11573342e+00,
         1.57096123e+00],
       [-1.24402268e-01, -8.29942503e-02, -8.42210287e-01,
        -5.22995685e-01, -4.41609463e-01, -6.76662289e-01,
        -5.18651970e-01, -6.74940735e-01, -6.01868187e-01,
        -5.77266023e-01, -7.88091685e-01, -5.94210655e-01,
        -7.28904365e-02, -7.88210355e-01, -3.61932945e-01,
         6.10931054e-01, -8.24455015e-01, -7.54396866e-01,
         9.29299002e-02,  3.18141033e-01,  5.76470743e-01,
         5.18816272e-03],
       [ 1.09378440e+00,  2.32462230e-01, -7.42590243e-01,
         1.06581905e+00, -3.92083168e-02,  1.31832480e+00,
         6.52171266e-01,  1.32079384e+00,  5.97262724e-01,
         5.27852988e-01,  8.22256709e-01,  4.80179365e-01,
         2.53585216e-01,  8.21704049e-01, -4.51687811e-01,
        -3.15656422e-01, -7.84138455e-02,  4.68199043e-01,
        -1.10748178e-01,  6.32072795e-01,  8.60326128e-01,
        -1.85434800e-01],
       [ 1.57463982e+00,  7.77040959e-01, -8.04476632e-01,
         2.24930400e-01, -4.41609463e-01,  2.33331824e-01,
         1.86429426e-01,  2.33060142e-01, -3.94885533e-01,
        -2.48470284e-01, -3.27992144e-01, -3.15574965e-01,
        -5.55209867e-01, -3.28087760e-01,  2.84346156e+00,
        -5.42991758e-01, -4.63136299e-01, -7.78552242e-01,
         2.26006912e-02, -5.34232072e-01,  6.91043111e-01,
        -6.82722000e-01],
       [-1.11483912e+00, -8.99104469e-01, -4.77176455e-01,
         3.98178815e-01,  7.65593976e-01,  4.85330193e-01,
         2.83458976e-01,  4.87487123e-01,  7.32400159e-01,
         4.18254408e-01,  8.71663371e-01,  5.66568597e-01,
         6.75614718e-01,  8.71113187e-01, -3.41881327e-01,
        -3.34156815e-01,  1.55342667e+00,  1.10764554e+00,
         6.93342979e-01,  2.45323176e-01, -1.01768833e+00,
         8.11136847e-01],
       [ 1.39454805e+00,  4.17479294e-01, -4.30415482e-01,
        -7.93107192e-02, -8.44010610e-01,  2.82331507e-01,
        -2.72843777e-01,  2.79743992e-01, -2.05864184e-01,
        -7.49391997e-02, -2.02931530e-01, -1.65914747e-01,
        -2.92436781e-01, -2.03535559e-01, -3.55249073e-01,
        -3.37606040e-01, -1.91668108e+00,  5.22225108e-02,
        -1.08529670e+00, -6.53046431e-01,  1.90695289e+00,
        -1.12578869e+00],
       [ 2.23398106e+00,  6.77775144e-01,  3.30873141e+00,
        -1.28359848e+00, -1.28665187e+00, -1.06865975e+00,
        -9.77925173e-01, -1.06941926e+00, -7.92600136e-01,
        -8.32996041e-01, -7.12437734e-01, -6.35580146e-01,
        -9.41975449e-01, -7.13067291e-01, -9.22423436e-01,
         7.61129160e-01, -7.34449158e-01, -1.25432806e+00,
        -1.44681476e+00, -1.84692800e+00, -2.31823791e-02,
        -1.44809578e+00],
       [-9.88738697e-01, -8.15642747e-01, -3.34337129e-01,
         3.89727673e-01,  7.65593976e-01,  6.25329287e-01,
         3.86957162e-01,  6.25204479e-01,  6.95424872e-02,
        -1.10066950e-02,  2.04673432e-01,  7.79967782e-04,
        -1.25217545e-01,  2.05119185e-01, -1.74784502e-01,
        -7.54021664e-01,  5.53243497e-01,  1.24321677e+00,
         7.95714122e-01, -1.11358128e+00,  2.86930432e-01,
         8.73480381e-01],
       [-4.19104054e-01, -3.46448799e-01, -2.83342105e-01,
         1.94896341e+00,  1.57039627e+00,  2.31931833e+00,
         1.07263265e+00,  2.31749403e+00,  4.33045081e-01,
         4.45654053e-01,  4.03844039e-01,  1.95459926e-01,
         3.36626061e-01,  4.03270414e-01,  2.29920334e+00,
        -4.41082814e-01,  1.44339368e+00, -1.38440051e+00,
         7.43045709e-01,  6.50784136e-01,  1.76136925e+00,
         6.72911406e-01]])

In [24]:
from sklearn.svm import SVC
model=SVC(kernel='linear')
model.fit(X_train,Y_train)

SVC(kernel='linear')

In [25]:
pred_train=model.predict(X_train)
from sklearn.metrics import accuracy_score

In [30]:
train_acc=accuracy_score(Y_train, pred_train)
train_acc

0.8717948717948718

In [33]:
pred_test=model.predict(X_test)
test_acc=accuracy_score(Y_test, pred_test)
test_acc

0.8717948717948718

Predictive model

In [43]:
input_data=(116.68200,	131.11100,	111.55500,	0.01050,	0.00009,	0.00544,	0.00781,	0.01633,	0.05233,	0.48200,	0.02757,	0.03858,	0.03590,	0.08270,	0.01309,	20.65100, 0.429895,	0.825288,	-4.443179,	0.311173,	2.342259,	0.332634)
input_array = np.asarray(input_data)
reshaped_data=input_array.reshape(1,-1)
std_data=scaler.transform(reshaped_data)
prediction=model.predict(std_data)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [44]:
prediction[0]

np.int64(1)

In [45]:
if prediction[0]==0:
  print("no parkinson")
else:
  print("parkinson disease detected")

parkinson disease detected